### ISSUE TITLE
Dependency markov-chain does not build with ghc-8.0.1

### ISSUE THREAD

**Issue by donya** [Euterpea/HSoM#3]
src\Data\MarkovChain.hs:18:29: error:
    Module `Control.Monad.State' does not export`State(State)'

markov-chain versions after 0.0.2 will also not install.

Tested on Windows 10 and OSX 10.10.5

**Comment by donya** [comment]
Temporary fix:
1. Download markov-chain 0.0.3.3 manually (cabal get markov-chain-0.0.3.3)
2. Edit line 34 of markov-chain.cabal to look like the following (the transformers <0.5 restriction needs to be lifted a bit): Build-Depends:   transformers >=0.0.1 && <0.6
3. Manually install with "cabal install" from the directory containing the .cabal file
4. Download and install HSoM.

This has been tested on both Windows 10 and OSX 10.10.5.

**Comment by donya** [comment]
A new version markov-chain has been released. Installing HSoM will now fetch markov-chain-0.0.3.4, which works with platform 8.0.1.
